// <auto-generated />
using System;
using Game_StoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game_StoreAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230724202019_AddPlatformTableToDatebase")]
    partial class AddPlatformTableToDatebase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game_StoreAPI.Models.GameCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstablishmentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("GameCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Nintendo Co., Ltd.[b] is a Japanese multinational video game company headquartered in Kyoto. It develops, publishes and releases both video games and video game consoles.",
                            EstablishmentDate = "23 September 1889",
                            ImageUrl = "https://persiadigest.com/wp-content/uploads/2022/05/3-new-SNES-and-NES-games-are-now-available.jpg",
                            Name = "Nintendo"
                        },
                        new
                        {
                            Id = 2,
                            Details = "Ubisoft Entertainment SA (/ˈjuːbisɒft/; French: [ybisɔft];[5] formerly Ubi Soft Entertainment SA) is a French video game publisher headquartered in Saint-Mandé with development studios across the world. Its video game franchises include Assassin's Creed, Far Cry, For Honor, Just Dance, Prince of Persia, Rabbids, Rayman, Tom Clancy's, and Watch Dogs.",
                            EstablishmentDate = "28 March 1986",
                            ImageUrl = "https://cloudfront-us-east-2.images.arcpublishing.com/reuters/YSIZCJEAI5PDDLYHNZZCI5F2FI.jpg",
                            Name = "Ubisoft"
                        },
                        new
                        {
                            Id = 3,
                            Details = "Electronic Arts Inc. (EA) is an American video game company headquartered in Redwood City, California.",
                            EstablishmentDate = "27 May 1982",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Electronic-Arts-Logo.svg/1200px-Electronic-Arts-Logo.svg.png",
                            Name = "Electronic Arts"
                        },
                        new
                        {
                            Id = 4,
                            Details = "Activision Blizzard, Inc.is an American video game holding company based in Santa Monica, California.",
                            EstablishmentDate = "10 July 2008",
                            ImageUrl = "https://www.videogameschronicle.com/files/2022/01/activision-blizzard-logo.jpg",
                            Name = "Activision Blizzard"
                        },
                        new
                        {
                            Id = 5,
                            Details = "Epic Games, Inc. is an American video game and software developer and publisher based in Cary, North Carolina. The company was founded by Tim Sweeney as Potomac Computer Systems in 1991, originally located in his parents' house in Potomac, Maryland.",
                            EstablishmentDate = "1991",
                            ImageUrl = "https://cdn2.unrealengine.com/epic-newsroom-share-1200x630-8c559c81a614.jpg",
                            Name = "Epic Games"
                        });
                });

            modelBuilder.Entity("Game_StoreAPI.Models.GameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GameTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "An adventure game (rarely called quest game) is a video game genre in which the player assumes the role of a protagonist in an interactive story, driven by exploration and/or puzzle-solving.",
                            AddedDate = new DateTime(2023, 7, 24, 23, 20, 19, 454, DateTimeKind.Local).AddTicks(1419),
                            Name = "Adventure game",
                            UpdatedDate = new DateTime(2023, 7, 24, 23, 20, 19, 454, DateTimeKind.Local).AddTicks(1482)
                        },
                        new
                        {
                            Id = 2,
                            About = "Action games emphasize physical challenges that require hand-eye coordination and motor skill to overcome. They center around the player, who is in control of most of the action. Most of the earliest video games were considered action games; today, it is still a vast genre covering all games that involve physical challenges.",
                            AddedDate = new DateTime(2023, 7, 24, 23, 20, 19, 454, DateTimeKind.Local).AddTicks(1488),
                            Name = "Action",
                            UpdatedDate = new DateTime(2023, 7, 24, 23, 20, 19, 454, DateTimeKind.Local).AddTicks(1492)
                        },
                        new
                        {
                            Id = 3,
                            About = "Simulation video games are a diverse super-category of video games, generally designed to closely simulate real world activities",
                            AddedDate = new DateTime(2023, 7, 24, 23, 20, 19, 454, DateTimeKind.Local).AddTicks(1496),
                            Name = "Simulation video game",
                            UpdatedDate = new DateTime(2023, 7, 24, 23, 20, 19, 454, DateTimeKind.Local).AddTicks(1500)
                        },
                        new
                        {
                            Id = 4,
                            About = "A sports video game is a video game that simulates the practice of sports. Most sports have been recreated with a video games, including team sports, track and field, extreme sports, and combat sports.",
                            AddedDate = new DateTime(2023, 7, 24, 23, 20, 19, 454, DateTimeKind.Local).AddTicks(1504),
                            Name = "Sports",
                            UpdatedDate = new DateTime(2023, 7, 24, 23, 20, 19, 454, DateTimeKind.Local).AddTicks(1507)
                        },
                        new
                        {
                            Id = 5,
                            About = "Platform games (or platformers) have gameplay primarily centered around jumping and climbing to navigate the player's environment. They may have enemies or obstacles to avoid and fight or may just be pure jumping puzzles.",
                            AddedDate = new DateTime(2023, 7, 24, 23, 20, 19, 454, DateTimeKind.Local).AddTicks(1512),
                            Name = "Platform game",
                            UpdatedDate = new DateTime(2023, 7, 24, 23, 20, 19, 454, DateTimeKind.Local).AddTicks(1515)
                        });
                });

            modelBuilder.Entity("Game_StoreAPI.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });
#pragma warning restore 612, 618
        }
    }
}
