// <auto-generated />
using System;
using Game_StoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game_StoreAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game_StoreAPI.Models.GameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GameTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "An adventure game (rarely called quest game) is a video game genre in which the player assumes the role of a protagonist in an interactive story, driven by exploration and/or puzzle-solving.",
                            AddedDate = new DateTime(2023, 7, 22, 18, 26, 5, 20, DateTimeKind.Local).AddTicks(1494),
                            Name = "Adventure game",
                            UpdatedDate = new DateTime(2023, 7, 22, 18, 26, 5, 20, DateTimeKind.Local).AddTicks(1543)
                        },
                        new
                        {
                            Id = 2,
                            About = "Action games emphasize physical challenges that require hand-eye coordination and motor skill to overcome. They center around the player, who is in control of most of the action. Most of the earliest video games were considered action games; today, it is still a vast genre covering all games that involve physical challenges.",
                            AddedDate = new DateTime(2023, 7, 22, 18, 26, 5, 20, DateTimeKind.Local).AddTicks(1546),
                            Name = "Action",
                            UpdatedDate = new DateTime(2023, 7, 22, 18, 26, 5, 20, DateTimeKind.Local).AddTicks(1547)
                        },
                        new
                        {
                            Id = 3,
                            About = "Simulation video games are a diverse super-category of video games, generally designed to closely simulate real world activities",
                            AddedDate = new DateTime(2023, 7, 22, 18, 26, 5, 20, DateTimeKind.Local).AddTicks(1549),
                            Name = "Simulation video game",
                            UpdatedDate = new DateTime(2023, 7, 22, 18, 26, 5, 20, DateTimeKind.Local).AddTicks(1550)
                        },
                        new
                        {
                            Id = 4,
                            About = "A sports video game is a video game that simulates the practice of sports. Most sports have been recreated with a video games, including team sports, track and field, extreme sports, and combat sports.",
                            AddedDate = new DateTime(2023, 7, 22, 18, 26, 5, 20, DateTimeKind.Local).AddTicks(1552),
                            Name = "Sports",
                            UpdatedDate = new DateTime(2023, 7, 22, 18, 26, 5, 20, DateTimeKind.Local).AddTicks(1554)
                        },
                        new
                        {
                            Id = 5,
                            About = "Platform games (or platformers) have gameplay primarily centered around jumping and climbing to navigate the player's environment. They may have enemies or obstacles to avoid and fight or may just be pure jumping puzzles.",
                            AddedDate = new DateTime(2023, 7, 22, 18, 26, 5, 20, DateTimeKind.Local).AddTicks(1555),
                            Name = "Platform game",
                            UpdatedDate = new DateTime(2023, 7, 22, 18, 26, 5, 20, DateTimeKind.Local).AddTicks(1557)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
